name: all

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  mobile-security:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      ##############################################
      # MobSFScan
      ##############################################
      - name: Run mobsfscan
        uses: MobSF/mobsfscan@a60d10a83af68e23e0b30611c6515da604f06f65
        with:
          args: . --sarif --output mobsfscan.sarif || true

      - name: Upload mobsfscan SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mobsfscan.sarif

      - name: Run MobSF Analysis on APK
        uses: MobSF/mobsfscan@a60d10a83af68e23e0b30611c6515da604f06f65
        with:
          args: 'InsecureBankv2.apk --sarif -o report-apk-scan.sarif --config .mobsf || true'

      - name: Upload mobsfscan SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-results
          path: mobsfscan.sarif

      - name: Upload APK scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report-apk-scan.sarif
          category: apk-scanning

      - name: Upload MobSF Analysis on APK result (if generated)
        uses: actions/upload-artifact@v4
        with:
          name: apk-scan-result
          path: report-apk-scan.sarif

      ##############################################
      # OWASP Dependency-Check
      ##############################################
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'flutter-app'
          format: 'SARIF'
          out: 'dependency-check'
          scan: '.'

      - name: Upload Dependency Check SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check/dependency-check-report.sarif

      - name: Upload Dependency Check SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-results
          path: dependency-check/dependency-check-report.sarif

      ##############################################
      # APKLeaks (optional APK secret scan)
      ##############################################
      - name: Install APKLeaks and jadx
        run: |
          pip install apkleaks
          wget https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-1.4.7.zip
          unzip -o -q jadx-1.4.7.zip
          sudo mv jadx-1.4.7/bin/jadx /usr/local/bin/
          sudo chmod +x /usr/local/bin/jadx



      - name: Run APKLeaks (if APK exists)
        run: |
          if [ -f InsecureBankv2.apk ]; then
            apkleaks -f InsecureBankv2.apk -o apkleaks_output.txt || true
          else
            echo "APK not found. Skipping APKLeaks."
          fi

      - name: Upload APKLeaks result (if generated)
        uses: actions/upload-artifact@v4
        with:
          name: apkleaks-result
          path: apkleaks_output.txt
